api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        pagination_items_per_page: 9
    collection:
        pagination:
            enabled: true

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
when@prod:
    api_platform:
        enable_swagger_ui: false
