security:
    password_hashers:
        App\Document\User:
            algorithm: auto

    providers:
        app_user_provider:
            mongodb:
                class: App\Document\User
                property: email

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: api_login
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/
            stateless: true
            jwt: ~

    access_control:
      - { path: ^/api, methods: [ OPTIONS ], roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/users/me, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/articles$, methods: [ GET ], roles: PUBLIC_ACCESS }
      - { path: ^/api/articles, methods: [ POST, PUT, PATCH, DELETE ], roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/api/login, roles: PUBLIC_ACCESS }
      - { path: ^/api/register, roles: PUBLIC_ACCESS }
